# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0061_auto_20180918_1355'),
        ('userstories', '0017_userstory_generated_from_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('expense', models.BigIntegerField(null=True)),
                ('profit', models.BigIntegerField(null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozit', to='projects.TaskStatus', verbose_name='status')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozits', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('user_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozits', to='userstories.UserStory', verbose_name='user story')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'funds',
            },
        ),
    ]
