# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20180918_1355'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='time_end',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='time_start',
        ),
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.ForeignKey(default=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='name'),
            preserve_default=False,
        ),
    ]
